print "I love lists, they were my favorite data"
print "structure before I discovered the next one"
print "you'll be learning about."
print "Lists are exactly what you think they would be."

print "Here's an example list."
print "[0, 1, 2, 3, 4]"
print "But those are just numbers."
print "It is helpful to define or name your lists."
print "my_pets = ['Johnny', 'Crosby', 'Olivia']"
print "The course will go into great detail later on lists."
print "For now, we are just going to learn how to iterate over"
print "a list. Python has the BEST syntax for traversing lists."
print "If you ever learn another language, you'll be mad it"
print "isn't this easy."
