print "So, I can't really test that you can do"
print "this set of skills... or at least I haven't"
print "figured out yet.  Keep forging ahead."
print "Input is useful, but also very easy and"
print "usually works the way you expect it to."
